language: java
jdk:
  - openjdk8
install: true
notifications:
  email:
    recipients:
    - hirorian1027@gmail.com
    on_success: always
    on_failure: always
after_success:
  - mvn clean test jacoco:report coveralls:jacoco
